### ISSUE TITLE
Configuration structure simplification

### ISSUE THREAD

**Issue by hyvs** [Elao/ElaoAdminBundle#8]
Can we try to simplify configuration structure : 

```
elao_admin:
    administrations:
        user:
            options:
                model: App\Domain\Model\User
            actions:
                list:
                    view: view.html.twig
```
instead of 
```
elao_admin:
    administrations:
        user:
            options:
                model: App\Domain\Model\User
            actions:
                list:
                    options:
                        parameters:
                            view: view.html.twig
```
